var GAME_LEVELS = [
  ["                                                                                                  ",
   "                                                                                                  ",
   "                                                                                                  ",
   "                                                                                                  ",
   "                                                                                                  ",
   "                                               oo                                                 ",
   "                                              xxxx       %               o                       x",
   "                                                     xx  xx     xxxxxx!!yyy!!xxxxxxxx           xx",
   "                                          xx                   xxxxxxx!!!!!!!xxxxxxxxx         xxx",
   "                                                              xxxxxxxx!!!!!!!xxxxxxxxxx        xxx",
   "                                      xx                o    xxxxxxxxx!!!!!!!xxxxxxxxxxx       xxx",
   "                                                       xxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxx o  xxx",
   "                                   x               o xxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxx    xxx",
   "             o                    xx         p   xxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxx o xxxx",
   "            xxx                  xxx!!!!yy!!yy!!!xxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxxx    xxx",
   "                                xxxx!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxo  xxx",
   "   @                  #        xxxxx!!!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxx    xxx",
   "xxxxxxxxxx      xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx o o      xxx",
   "xxxxxxxxxx!!yy!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx o o     xxxx",
   "xxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx o o      xxx",
   "xxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                              ",
   "            xxxx!!!!!!!xxxx                                                                   ",
   "                   v                                                                          ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                         !!!! ",
   "                                                                                      !!!!!!!!",
   "                                        %                                      !!!!!!!!!!!!!xx",
   "                  xxx          |                                             xx!!xxxxxxxxxxxxx",
   "                        xxxx      oo      o o        xxxxxxx                   v             x",
   "              o         x!!!!!!!!yyyy!!!!yyyyy!!!!xxxxxxxxxx                                 x",
   "             xxx        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                                 x",
   "                        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx  xxx                           x",
   "                   xx   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx                                x",
   "                        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx       xxx                      x",
   "                        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx %                             xx",
   "                 xx     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx                             xx",
   "                        xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx      xxx                   o  xx",
   "                       xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx                #           xxxxx",
   "               xxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx #            xxx       xxxxxxxx",
   "             xxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxx",
   "     @      xxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o    xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                          xxxxx                ",
   "                                                                                         xx!!!xx               ",
   "                            #                                                            xx!!!xx               ",
   "                                                       xxxxxxxxx                          xx!xx                ",
   "                                                     xxxx      xx                           v                  ",
   "                        o       o                   xxx  o                                                     ",
   "                       xxx     xxx                   xxxx                                             #        ",
   "                        xx!!!!!xx                      xxxxxx         #  oo                                    ",
   "                         xx!!!xx                                   xxxxxxxxxxxxx                               ",
   "                            v          x                        xxxx           xx                              ",
   "                                             xxx               xx               xxx                            ",
   "                                                     %        xx               y  xxxxxxxx                     ",
   "                                                    xxx                        yy                              ",
   "                                           xxxx                                yyy                 o           ",
   "@                                                          xxx                 yyyy              xxxx          ",
   "x                                xxxxx   |                                     yyyyy           |               ",
   "xx                                                                             yyyyyy                          ",
   "xxxx                       o                                                   yyyyyyy     xxxx                ",
   "xxxxx                    xxxxx                                                 y                               ",
   "xxxxxxx                                            #                           y  o                            ",
   "xxxxxxxxxxxxxxxx!!!yyyy!!!!!!!!!!yyyyyy!!!!!!!!!!yyyyyy!!!!!yyyyy!!!!!!!yyyyyyyyyyyyyy!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!yyyyyyyyyy!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!yyyyyyyy!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!yyyy!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   "                                                                                                              ",
   "       ooooooo     oooooo       oooooooooo         ooooooo        ooooooo                                     ",
   "         oooooo   ooooo       oooooooooooooo        ooooo          ooooo                                      ",
   "           ooooo ooooo       oooo        oooo       ooooo          ooooo                                      ",
   "            ooooooooo       oooo          oooo      ooooo          ooooo                                      ",
   "              ooooo         oooo          oooo      ooooo          ooooo                                      ",
   "              ooooo         oooo          oooo       ooooo        ooooo                                       ",
   "              ooooo          oooo        oooo         ooooo      ooooo                                        ",
   "              ooooo           ooooooooooooooo           ooooooooooooo                                         ",
   "             ooooooo            ooooooooooo              oooooooooo                                           ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                          oo                                                  ",
   "                   o             o    o     o      o      oo                                                  ",
   "                    o     o     o     o     o o    o      oo                                                  ",
   "                     o  o   o  o      o     o   o  o                                                          ",
   "                      o       o       o     o     oo      oo                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
